export type Resena = {
  name: string;
  origin: string;
  year: string;
  quote: string;
  color: "clay" | "moss" | "wood" | "forest";
  rotate: number;
  scale: number;
  mirror?: boolean;
};

export const resenas: Resena[] = [
  {
    name: "Aki M.",
    origin: "Argentina",
    year: "2026",
    quote: "El lugar nos encantó. Desayuno con dulces caseros riquísimos y propuestas de trekking guiado. Muy buena atención en todo momento.",
    color: "clay",
    rotate: -12,
    scale: 1,
  },
  {
    name: "Iaru M.",
    origin: "Argentina",
    year: "2026",
    quote: "Llegamos de la montaña bajo la lluvia. Nos ofrecieron un té calentito y dormimos genial.",
    color: "moss",
    rotate: 8,
    scale: 0.92,
    mirror: true,
  },
  {
    name: "Belén C.",
    origin: "Argentina",
    year: "2026",
    quote: "Limpio, acogedor, cocina completa. Los mimos de Gorda, la gatita del hostel, un lujo.",
    color: "wood",
    rotate: -6,
    scale: 1.05,
  },
  {
    name: "Cassandra B.",
    origin: "Argentina",
    year: "2026",
    quote: "Estuve un mes y se sintió como un hogar. Comidas en familia con huéspedes, voluntarios y lugareños.",
    color: "forest",
    rotate: 14,
    scale: 0.95,
    mirror: true,
  },
  {
    name: "Maximiliano F.",
    origin: "Argentina",
    year: "2026",
    quote: "Maravilloso lugar. Cálido, limpio y con una energía hermosa.",
    color: "clay",
    rotate: -18,
    scale: 1,
  },
  {
    name: "Marian M.",
    origin: "Argentina",
    year: "2026",
    quote: "Muy buena ubicación, desayuno con dulces caseros y propuestas de trekking. Muy buena atención.",
    color: "moss",
    rotate: 10,
    scale: 0.9,
    mirror: true,
  },
  {
    name: "Carla M.",
    origin: "Argentina",
    year: "2026",
    quote: "Desayuno con budín y mermeladas caseras. Los voluntarios, la mejor energía. Voy a volver.",
    color: "clay",
    rotate: -8,
    scale: 1.08,
  },
  {
    name: "Carlos C.",
    origin: "Argentina",
    year: "2026",
    quote: "Maxi siempre atento. Excelentes propuestas de senderismo en lugares poco visitados. Gran calidez.",
    color: "wood",
    rotate: 16,
    scale: 0.94,
    mirror: true,
  },
  {
    name: "Nico G.",
    origin: "Argentina",
    year: "2026",
    quote: "Súper cómodo y limpio. Una experiencia única para conocer Lago Puelo. Muy feliz con todo.",
    color: "forest",
    rotate: -10,
    scale: 1,
  },
  {
    name: "Fer L.",
    origin: "Argentina",
    year: "2025",
    quote: "La habitación cumplió mis expectativas. Limpio y se nota la inversión que hacen los dueños.",
    color: "clay",
    rotate: 6,
    scale: 1.02,
    mirror: true,
  },
  {
    name: "Jesica B.",
    origin: "Argentina",
    year: "2026",
    quote: "Lugar muy agradable. La cama súper cómoda y la limpieza impecable.",
    color: "moss",
    rotate: -14,
    scale: 0.96,
  },
  {
    name: "Isidro C.",
    origin: "Argentina",
    year: "2026",
    quote: "Muy lindo lugar, cómodo y buena gente. Muy recomendable.",
    color: "wood",
    rotate: 12,
    scale: 1.04,
    mirror: true,
  },
  {
    name: "María",
    origin: "Argentina",
    year: "2026",
    quote: "Si querés sentirte como en casa en tus vacaciones, este es el lugar. Gracias Maxi y familia.",
    color: "forest",
    rotate: -20,
    scale: 0.91,
  },
  {
    name: "Martín M.",
    origin: "Argentina",
    year: "2026",
    quote: "Tranquilo, cálido y agradable. Corre un arroyo por el patio, muy lindo.",
    color: "clay",
    rotate: 7,
    scale: 1.01,
    mirror: true,
  },
  {
    name: "Estefanía S.",
    origin: "Argentina",
    year: "2025",
    quote: "Ambiente súper cálido y espacios lindos. Maxi nos orientó y fue nuestro guía. Volvería a elegirlo.",
    color: "moss",
    rotate: -9,
    scale: 0.97,
  },
  {
    name: "Natalia H.",
    origin: "Argentina",
    year: "2025",
    quote: "Un lugar para soñar. Maxi un genio, el patio mágico, la ubicación excelente. Ya quiero volver.",
    color: "wood",
    rotate: 18,
    scale: 0.93,
    mirror: true,
  },
  {
    name: "Agustín C.",
    origin: "Argentina",
    year: "2025",
    quote: "Cómodo y accesible. Maxi oriundo de Puelo te atiende muy bien y es guía para trekkings.",
    color: "clay",
    rotate: -15,
    scale: 1.06,
  },
  {
    name: "Sabrina G.",
    origin: "Argentina",
    year: "2026",
    quote: "Excelente lugar para descansar y disfrutar del paisaje.",
    color: "forest",
    rotate: 11,
    scale: 0.98,
    mirror: true,
  },
  {
    name: "Sabrina C.",
    origin: "Argentina",
    year: "2025",
    quote: "Habitación amplia con hermosa vista. Super limpio y muy buena onda todo el staff.",
    color: "moss",
    rotate: -5,
    scale: 1.03,
  },
];
